name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main # Adjusted to trigger on pushes to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sorak007/urlshorten:latest

      - name: Verify Pushed Image
        run: docker pull sorak007/urlshorten:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull sorak007/urlshorten:latest
            sudo docker stop url_shorten || true
            sudo docker rm url_shorten || true
            sudo docker run --restart=always -d --env-file ./.env.prod --name url_shorten -p 8080:8080 sorak007/urlshorten:latest
